version: '3'
services:
  haproxy:
    image: robwilkes/haproxy
    cap_add:
     - NET_ADMIN
    network_mode: host
    ports:
     - "443:443"
     - "1936:1936"
    volumes:
     - /usr/local/etc/haproxy:/usr/local/etc/haproxy
    restart: unless-stopped
    depends_on:
     - exabgp
  exabgp:
    image: robwilkes/exabgp
    cap_add:
     - NET_ADMIN
    network_mode: host
    ports:
     - "179:179"
    volumes:
     - /usr/local/etc/exabgp:/usr/local/etc/exabgp
    restart: unless-stopped