version: '3'
services:
  haproxy:
    image: robwilkes/haproxy
    cap_add:
     - NET_ADMIN
    network_mode: host
    ports:
     - "80:80"
     - "1936:1936"
    volumes:
     - /usr/local/haproxy/etc:/usr/local/haproxy/etc