version: '3'
services:
  exabgp:
    image: robwilkes/exabgp
    cap_add:
     - NET_ADMIN
    network_mode: host
    ports:
     - "179:179"
    volumes:
     - /usr/local/exabgp/etc:/usr/local/exabgp/etc